packages:
  # all packages in direct subdirs of packages/
  - 'packages/**'
  - 'examples/**'
  - '!packages/templates/templates/**'
  - '!packages/templates'
  - '!packages/tsconfig'
  - '!packages/cli'
